language: php

php:
  - 5.5

cache:
  directories:
    - vendor
    - node_modules
    - bower_components

before_script:
  - mysql -e 'create database sharepear;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --prefer-dist
  - app/console doctrine:migration:migrate -n
  - app/console doctrine:fixtures:load -n
  - app/console assets:install --symlink
  - npm install
  - node_modules/.bin/grunt
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - phpunit -c app
  - app/console doctrine:migration:migrate -n --env=test 0

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php bin/coveralls -v
