language: php

php:
  - 5.5

cache:
  directories:
    - vendor
    - node_modules
    - bower_components

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --prefer-dist
  - app/console doctrine:database:create
  - app/console doctrine:schema:create
  - app/console assets:install --symlink
  - node_modules/.bin/grunt

script:
  - phpunit -c app
