kosssi_my_albums:
    resource: "@kosssiMyAlbumsBundle/Controller/"
    type:     annotation
    prefix:   /

oneup_uploader:
    resource: .
    type: uploader

_imagine:
    resource: .
    type:     imagine
