login_check:
    pattern:   /verification

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

kosssi_user:
    resource: "@kosssiUserBundle/Controller/"
    type:     annotation
    prefix:   /

kosssi_my_albums:
    resource: "@kosssiMyAlbumsBundle/Controller/"
    type:     annotation
    prefix:   /

oneup_uploader:
    resource: .
    type: uploader

_imagine:
    resource: .
    type:     imagine
